### ISSUE TITLE
How to obtain correct labels for each directory?

### ISSUE THREAD

**Issue by JingyeChen** [callee2006/HangulDB#2]
Thank you for your hard work! However, I got into a dilemma when using the SERI dataset. That is, after I unzipped SERI_Test.zip, I found that the names of directories range from “b0a1” to “c8fb”. Moreover, images under the directory “b0a1” are 가, which is encoded with “ac00” in the Unicode standard instead of“b0a1”. The same problem also exists in other directories. So how to get the correct labels for each directory? I am looking forward to your reply :)

**Comment by hyangyu** [comment]
I have the same problem when doing research

**Comment by callee2006** [comment]
The character encoding of the dataset is not UNICODE but KS-5601. You can download KS-5601 chart from https://ycswarm.tistory.com/attachment/cfile28.uf@2121F03F53A3BA2A12D2A1.pdf .

**Comment by JingyeChen** [comment]
Thank you for your reply! :) I will search KS-5601 for more information.
